name: churn_dashboard
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  csv: ^5.1.1
  cupertino_icons: ^1.0.6
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  go_router: ^13.2.0
  provider: ^6.1.1

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/data/
    - assets/images/
    - assets/screenshots/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.jpg"